import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { GPT_HOST_RESPONSE_SCHEMA, GPT_POLICY_JUDGE_RESPONSE_SCHEMA, compileGptHostRequest, compileAgentPolicyJudgeRequest, compileRetryRequest, decideAgentDelivery } from '../src/index.mjs'
const research = JSON.parse(fs.readFileSync(new URL('../profiles/research.profile.json', import.meta.url)))
function draft(message){return {schema:GPT_HOST_RESPONSE_SCHEMA,message,action:{kind:'research-plan',conclusionStatus:'blocked',conclusionDirection:'undetermined',rationale:'continue validation',claim:null,plan:'continue validation'},citations:[]}}
function req(msg='只按当前 Host 状态更新，不把单条证据升级为真理。'){return compileGptHostRequest(research,structuredClone(research.initialState),{userMessage:msg})}
test('RC7 certainty overreach uses Host-owned repair',()=>{const r=req();const x=compileRetryRequest(r,{status:'blocked',reason:'policy-violation',violations:[{code:'RESEARCH_CERTAINTY_OVERREACH',evidenceQuote:'已证实'}]});assert.equal(x.responseContract.hostOwnedMessage,true);assert.match(x.responseContract.jsonSchema.properties.message.enum[0],/(?:结论仍未定|conclusion remains undetermined)/iu)})
test('RC7 blocks Research action-label-only user-visible prose',()=>{const r=req();for(const m of ['research-plan','report-with-profile-caveats']){const j=compileAgentPolicyJudgeRequest(r,draft(m),{});assert.ok(j.deterministicViolations.some(v=>v.code==='RESEARCH_USER_VISIBLE_PLACEHOLDER'))}})
test('RC7 detects evidence/validation provenance cross-wire and Judge sees method/confidence',()=>{const r=req('调用 evidence:E');r.evidence=[{evidenceId:'evidence:E',stance:'support',summary:'Experiment E reproduces lower central variance for method A.',source:{locator:'app://research/s1/source-E',title:'Sustained Experiment E'}}];r.validation=[{validationId:'validation:V1',method:'pre-registered sustained rerun V1',outcome:'support',confidence:.95,reproducible:true,strong:true,provenance:{locator:'app://research/s1/validation-V1'}}];const j=compileAgentPolicyJudgeRequest(r,draft('基于现有证据 E，该证据来自 pre-registered sustained rerun V1，置信度0.95，可重复性true。'),{});assert.ok(j.deterministicViolations.some(v=>v.code==='RESEARCH_PROVENANCE_MISATTRIBUTION'));assert.equal(j.immutablePolicy.validation[0].method,'pre-registered sustained rerun V1');assert.equal(j.immutablePolicy.validation[0].confidence,.95)})
test('RC7 placeholder/provenance repair is Host-owned clean prose',()=>{const r=req();for(const code of ['RESEARCH_USER_VISIBLE_PLACEHOLDER','RESEARCH_PROVENANCE_MISATTRIBUTION']){const x=compileRetryRequest(r,{status:'blocked',reason:'policy-violation',violations:[{code,evidenceQuote:'research-plan'}]});const m=x.responseContract.jsonSchema.properties.message.enum[0];assert.equal(x.responseContract.hostOwnedMessage,true);assert.ok(m.length>13);assert.equal(/"action"\s*:|"kind"\s*:/iu.test(m),false)}})
test('RC7 Host-owned Research repair suppresses unsupported certainty false positive',()=>{const r=req();const x=compileRetryRequest(r,{status:'blocked',reason:'policy-violation',violations:[{code:'RESEARCH_CERTAINTY_OVERREACH',evidenceQuote:'已证实'}]});const m=x.responseContract.jsonSchema.properties.message.enum[0];const d=draft(m);const jr=compileAgentPolicyJudgeRequest(x,d,{});const q=jr.evidenceQuoteCandidates[0];const jd={schema:GPT_POLICY_JUDGE_RESPONSE_SCHEMA,compliant:false,confidence:1,violations:[{code:'RESEARCH_CERTAINTY_OVERREACH',evidenceQuote:q,rationale:'false positive'}]};assert.equal(decideAgentDelivery(x,d,jr,jd).status,'deliver')})
